server:
  port: 9999
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: ylfjm-gateway-system
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      #----------------------------------------------------
      - id: ylfjm-service-auth
        uri: lb://ylfjm-service-auth
        predicates:
          - Path=/api/auth/**
        filters:
        - StripPrefix=2
      #----------------------------------------------------
      - id: ylfjm-service-system
        uri: lb://ylfjm-service-system
        predicates:
        - Path=/api/system/**
        filters:
        - StripPrefix=2
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: ${spring.cloud.client.ip-address}
    lease-renewal-interval-in-seconds: 5 # 默认30秒
    lease-expiration-duration-in-seconds: 10 # 默认90秒
    metadata-map:
      zone: zone-1
  client:
    prefer-same-zone-eureka: true
    region: shanghai
    availability-zones:
      shanghai: zone-1
    registry-fetch-interval-seconds: 5 # 默认30秒
    instance-info-replication-interval-seconds: 5 # 默认为30秒
    service-url:
      defaultZone: http://ylfjm:123456@localhost:30000/eureka
      zone-1: http://ylfjm:123456@localhost:30000/eureka